include:
# zen kb
  - board: corneish_zen_v2_left
    artifact-name: zen_left
  - board: corneish_zen_v2_right
    artifact-name: zen_right
# dongle corne
  - board: seeeduino_xiao_ble
    shield: crpd_dongle prospector_adapter
    artifact-name: corne_dongle
  - board: nice_nano_v2
    shield: crpd_central_left nice_view_adapter nice_view
    artifact-name: corne_central_left
  - board: nice_nano_v2
    shield: crpd_left nice_view_adapter nice_view
    artifact-name: corne_left
  - board: nice_nano_v2
    shield: crpd_right nice_view_adapter nice_view
    artifact-name: corne_right
# reset settings
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_nano_rest
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xioa_rest
