include:
# zen kb
  - board: corneish_zen_v2_left
  - board: corneish_zen_v2_right
# dongle corne
  - board: seeeduino_xiao_ble
    shield: crpd_dongle prospector_adapter
  - board: nice_nano_v2
    shield: crpd_central_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: crpd_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: crpd_right nice_view_adapter nice_view
# reset settings
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
