layout: {zmk_keyboard: base}
layers:
  BASE:
  - \
  - Q
  - W
  - E
  - R
  - T
  - Y
  - U
  - I
  - O
  - P
  - '['
  - CAPS
  - {t: A, h: '$$mdi:apple-keyboard-control$$'}
  - {t: S, h: '$$mdi:apple-keyboard-option$$'}
  - {t: D, h: '$$mdi:apple-keyboard-command$$'}
  - {t: F, h: '$$mdi:apple-keyboard-shift$$'}
  - G
  - H
  - {t: J, h: '$$mdi:apple-keyboard-shift$$'}
  - {t: K, h: '$$mdi:apple-keyboard-command$$'}
  - {t: L, h: '$$mdi:apple-keyboard-option$$'}
  - {t: ;, h: '$$mdi:apple-keyboard-control$$'}
  - ''''
  - ''
  - Z
  - X
  - C
  - {t: V, h: '$$mdi:web$$'}
  - B
  - N
  - {t: M, h: '$$mdi:web$$'}
  - ','
  - .
  - /
  - ']'
  - {t: '$$mdi:keyboard-esc$$', h: MOUSE}
  - {t: '$$mdi:keyboard-tab$$', h: NAV}
  - {t: '$$mdi:keyboard-space$$', h: SYM}
  - {t: '$$mdi:keyboard-return$$', h: NUM}
  - {t: '$$mdi:backspace-outline$$', h: FN}
  - {t: '$$mdi:backspace-reverse-outline$$', h: CONF}
  SYM:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {t: '?', s: '!'}
  - {t: '[', s: '{'}
  - {t: '''', s: '"'}
  - {t: ']', s: '}'}
  - {t: '=', s: '~'}
  - ''
  - ''
  - $$mdi:apple-keyboard-control$$
  - $$mdi:apple-keyboard-option$$
  - $$mdi:apple-keyboard-command$$
  - $$mdi:apple-keyboard-shift$$
  - ''
  - {t: '-', s: +}
  - {t: (, s: <}
  - {t: /, s: \}
  - {t: ), s: '>'}
  - {t: '@', s: '&'}
  - ''
  - ''
  - ''
  - ''
  - ''
  - $$mdi:web$$
  - ''
  - {t: '#', s: '*'}
  - {t: ^, s: '%'}
  - {t: '|', s: _}
  - {t: $, s: '`'}
  - {t: ':', s: ;}
  - ''
  - $$mdi:keyboard-esc$$
  - $$mdi:keyboard-tab$$
  - {type: held}
  - ''
  - $$mdi:backspace-outline$$
  - $$mdi:backspace-reverse-outline$$
  NUM:
  - ''
  - '1'
  - '2'
  - '3'
  - '4'
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - '5'
  - '6'
  - '7'
  - '8'
  - ''
  - ''
  - $$mdi:apple-keyboard-shift$$
  - $$mdi:apple-keyboard-command$$
  - $$mdi:apple-keyboard-option$$
  - $$mdi:apple-keyboard-control$$
  - ''
  - ''
  - '9'
  - '0'
  - '-'
  - '='
  - ''
  - ''
  - $$mdi:web$$
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - $$mdi:keyboard-space$$
  - {type: held}
  - $$mdi:backspace-outline$$
  - $$mdi:backspace-reverse-outline$$
  FN:
  - ''
  - $$mdi:keyboard-f1$$
  - $$mdi:keyboard-f2$$
  - $$mdi:keyboard-f3$$
  - $$mdi:keyboard-f4$$
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - $$mdi:keyboard-f5$$
  - $$mdi:keyboard-f6$$
  - $$mdi:keyboard-f7$$
  - $$mdi:keyboard-f8$$
  - ''
  - ''
  - $$mdi:apple-keyboard-shift$$
  - $$mdi:apple-keyboard-command$$
  - $$mdi:apple-keyboard-option$$
  - $$mdi:apple-keyboard-control$$
  - ''
  - ''
  - $$mdi:keyboard-f9$$
  - $$mdi:keyboard-f10$$
  - $$mdi:keyboard-f11$$
  - $$mdi:keyboard-f12$$
  - ''
  - ''
  - $$mdi:web$$
  - ''
  - ''
  - ''
  - ''
  - $$mdi:keyboard-esc$$
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  NAV:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - Home
  - Page Down
  - Page Up
  - End
  - ''
  - ''
  - $$mdi:apple-keyboard-control$$
  - $$mdi:apple-keyboard-option$$
  - $$mdi:apple-keyboard-command$$
  - $$mdi:apple-keyboard-shift$$
  - ''
  - $$mdi:arrow-left-bold$$
  - $$mdi:arrow-down-bold$$
  - $$mdi:arrow-up-bold$$
  - $$mdi:arrow-up-bold$$
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - $$mdi:web$$
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - $$mdi:backspace-outline$$
  - $$mdi:backspace-reverse-outline$$
  MOUSE:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - $$mdi:transfer-left$$
  - $$mdi:transfer-down$$
  - $$mdi:transfer-up$$
  - $$mdi:transfer-right$$
  - ''
  - ''
  - $$mdi:apple-keyboard-control$$
  - $$mdi:apple-keyboard-option$$
  - $$mdi:apple-keyboard-command$$
  - $$mdi:apple-keyboard-shift$$
  - ''
  - $$mdi:arrow-left-bold-outline$$
  - $$mdi:arrow-down-bold-outline$$
  - $$mdi:arrow-up-bold-outline$$
  - $$mdi:arrow-right-bold-outline$$
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  - ''
  - ''
  - $$mdi:mouse-left-click$$
  - $$mdi:mouse-right-click$$
  - $$mdi:mouse-scroll-wheel$$
  CONF:
  - $$mdi:skip-next$$
  - {t: BT, h: '0', s: Clr BT 0}
  - {t: BT, h: '1', s: Clr BT 1}
  - {t: BT, h: '2', s: Clr BT 2}
  - {t: BT, h: '3', s: Clr BT 3}
  - {t: BT, h: '4', s: Clr BT 4}
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - PP
  - $$mdi:brightness-5$$
  - $$mdi:brightness-7$$
  - $$mdi:volume-medium$$
  - $$mdi:volume-high$$
  - $$mdi:volume-variant-off$$
  - ''
  - $$mdi:apple-keyboard-shift$$
  - $$mdi:apple-keyboard-command$$
  - $$mdi:apple-keyboard-option$$
  - $$mdi:apple-keyboard-control$$
  - ''
  - PREV
  - ''
  - ''
  - ''
  - $$mdi:chip$$
  - $$mdi:cog-refresh$$
  - $$mdi:cog-refresh$$
  - $$mdi:chip$$
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - {type: held}
  GAME: ['$$mdi:keyboard-esc$$', Q, W, E, R, T, Y, U, I, O, P, '', '$$mdi:keyboard-tab$$', A, S, D, F, G, H, J, K, L, ;, '', '$$mdi:apple-keyboard-shift$$', Z, X,
    C, V, B, N, M, ',', ., /, '', '$$mdi:apple-keyboard-option$$', '$$mdi:apple-keyboard-control$$', '$$mdi:keyboard-space$$', '$$mdi:keyboard-return$$', '$$mdi:backspace-outline$$',
    GAME_N]
  GAME_N:
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - '1'
  - '2'
  - '3'
  - '4'
  - '5'
  - '6'
  - '7'
  - '8'
  - '9'
  - '0'
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {t: '$$mdi:menu-down-outline$$', type: trans}
  - {type: held}
combos:
- p: [38, 39]
  k: $$mdi:controller$$
  l: [BASE]
  a: top
  o: 0.5
- p: [38, 39]
  k: $$mdi:controller-off$$
  l: [GAME]
  a: top
  o: 0.5
