name: Build ZMK firmware

on:
  push:
    paths-ignore:
      - 'images/**'
      - 'keymap-drawer.config.yaml'
      - 'keymap/**'
      - '.vscode/**'
      - 'README.md'
      - '.gitattributes'

permissions:
  contents: read
  packages: read

jobs:
  build_zen:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: corneish_zen_v2_left
            artifact: zen_left
          - board: corneish_zen_v2_right
            artifact: zen_right
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull build container
        run: docker pull ghcr.io/zmkfirmware/zmk-dev-arm:stable

      - name: Initialize West workspace
        run: |
          docker run --rm -v "${{ github.workspace }}:/workdir" -w /workdir ghcr.io/zmkfirmware/zmk-dev-arm:stable bash -lc "west init -l config && west update"

      - name: Build (ZMK fork for Zen)
        run: |
          docker run --rm -v "${{ github.workspace }}:/workdir" -w /workdir ghcr.io/zmkfirmware/zmk-dev-arm:stable bash -lc "west build -s zmk-zen/app -b ${{ matrix.board }} -- -DZMK_CONFIG=/workdir/config"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            build/zephyr/*.uf2
            build/zephyr/*.hex
            build/zephyr/*.bin

  build_others:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - board: nice_nano_v2
            shield: "crpd_central_left nice_view_adapter nice_view"
            artifact: corne_central_left
          - board: nice_nano_v2
            shield: "crpd_left nice_view_adapter nice_view"
            artifact: corne_left
          - board: nice_nano_v2
            shield: "crpd_right nice_view_adapter nice_view"
            artifact: corne_right
          - board: seeeduino_xiao_ble
            shield: "crpd_dongle prospector_adapter"
            artifact: corne_dongle
          - board: nice_nano_v2
            shield: settings_reset
            artifact: nice_nano_rest
          - board: seeeduino_xiao_ble
            shield: settings_reset
            artifact: xioa_rest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull build container
        run: docker pull ghcr.io/zmkfirmware/zmk-dev-arm:stable

      - name: Initialize West workspace
        run: |
          docker run --rm -v "${{ github.workspace }}:/workdir" -w /workdir ghcr.io/zmkfirmware/zmk-dev-arm:stable bash -lc "west init -l config && west update"

      - name: Build (upstream ZMK)
        run: |
          docker run --rm -v "${{ github.workspace }}:/workdir" -w /workdir ghcr.io/zmkfirmware/zmk-dev-arm:stable bash -lc "west build -s zmk/app -b ${{ matrix.board }} -- -DSHIELD=\"${{ matrix.shield }}\" -DZMK_CONFIG=/workdir/config"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: |
            build/zephyr/*.uf2
            build/zephyr/*.hex
            build/zephyr/*.bin
